### ISSUE TITLE
Server Crash when lama spawns.

### ISSUE THREAD

**Issue by Joulanh** [ArshiaDPG/Llamarama#1]
I dont know the exact reason why but my server crashes every time a lama spawns naturally, at least that is what i think. The error says its a ticking issue with a lama. Happened 5 or more times so far in the overworld and the end and with diffrent lamas from the mod.  Ill link the last [ Crashlog](https://pastebin.com/X31PunSA) . Maybe it has something to do with the other mods i have installed, they should be listed at the end of the crashlog. Would be cool if you can help me and if needed i can add a clearer list of all the mods installed.

**Comment by 0xJoeMama** [comment]
Can you specify the version of the mod that you are using?

**Comment by Joulanh** [comment]
Version 1.3.1

**Comment by 0xJoeMama** [comment]
Can you try seeing if the issue still exists in 1.3.2?

**Comment by 0xJoeMama** [comment]
Because even though they are not listed there were some changes that May affect this

**Comment by 0xJoeMama** [comment]
Also is this normal spawning or is it trader spawning that is causing this issue?

**Comment by Joulanh** [comment]
ah ok i will try it tomorrow evening(CET) if thats fine

**Comment by 0xJoeMama** [comment]
> Also is this normal spawning or is it trader spawning that is causing this issue? 

Can you reply to this?

**Comment by 0xJoeMama** [comment]
> ah ok i will try it tomorrow evening(CET) if thats fine
> 

Just send the answer here I'll be on it if I see it

**Comment by Joulanh** [comment]
I had crashes with the normal lama, the wooly lama and the bumble lama. Some kind of Caravan Goal seems to be related but im not sure if i understand the crashlog correctly. 

![image](https://user-images.githubusercontent.com/80494384/113052968-1226d480-91a8-11eb-9eb8-f625007a4e2d.png)

**Comment by 0xJoeMama** [comment]
> I had crashes with the normal lama, the wooly lama and the bumble lama. Some kind of Caravan Goal seems to be related but im not sure if i understand the crashlog correctly.
> 
> ![image](https://user-images.githubusercontent.com/80494384/113052968-1226d480-91a8-11eb-9eb8-f625007a4e2d.png)

I have found the solution to the problem. Thank you for your report. This issue will be closed once a new release comes out.
