### ISSUE TITLE
Config options for caravan trader.

### ISSUE THREAD

**Issue by Joulanh** [ArshiaDPG/Llamarama#10]
It would be really nice to have some config options for the caravan trader, for example spawn rate / time between spawns and a llama blacklist of some sort.

**Comment by 0xmycf** [comment]
What exactly did you wanna change? Is the trader spewing too frequently/rarely for your taste? Or is it just a general wish for the mod to be more configurable?

**Comment by Joulanh** [comment]
in my case id like to disable the mossy lama spawning with the caravan trader.

**Comment by 0xJoeMama** [comment]
Hello there!

Firstly, thank you for reporting this issue.
Secondly I would like to say that the config option you are asking for, already exists, in the form of [tags](https://minecraft.fandom.com/wiki/Tag).
If that does not suffice, I'd like to hear what you suggest as an alternative to using a config API.
The reason for that is because we are trying to not use a config API. Mostly because we try to make dependency free mods.

Again, thank you for the report!

**Comment by 0xJoeMama** [comment]
I would also like to reference [this](https://github.com/LlamaramaTeam/Llamarama/blob/master/src/main/resources/data/llamarama/tags/entity_types/llamas.json) as it is the tag that manages the kinds of llamas that will spawn with caravan traders.

**Comment by Joulanh** [comment]
I have to admit I'm pretty much a novice when it comes to server management and mod development so i have no idea how to control mob spawning with tags. Is there a helpful tutorial you know of ? I've read through some pages on the wiki and am still at square one xd.

Since im not a dev i cant really give you an alternative, the only thing I know is that there are mods, like for example apple skin, that have no dependencys but still generate and use a config.

**Comment by 0xJoeMama** [comment]
> so i have no idea..spawning

Well the purpose of the tag isn't to control mob spawning here. This tag is just a group of the mobs the caravan trader can spawn with.

**Comment by 0xJoeMama** [comment]
Also, regarding the AppleSkin thing, I looked into it.
Turns out the Cloth Config API is included to its classpath with fat-jarring. However that can cause a lot of issues and is generally not recommended in modding.

**Comment by 0xJoeMama** [comment]
Obviously, I cannot criticize the creator of AppleSkin of course. Since it has caused no issues to him he has no issues continuing on with it. However that is not the strategy I would like to follow.

**Comment by 0xJoeMama** [comment]
I think I am going to close this. If you would like to add something to the conversation do so until Monday. After that the issue will be closed. Thank you for your feedback as always!

**Comment by 0xJoeMama** [comment]
I will be closing this. Thank you for your support as always!
