### ISSUE TITLE
Crash involving Bumble Llama

### ISSUE THREAD

**Issue by Wpgradford** [ArshiaDPG/Llamarama#14]
Hi! Loving the mod, but I recently crashed a few minutes after the wandering llama trader guy showed up. Here's the crash log: [crash-2022-03-29_14.12.17-client.txt](https://github.com/LlamaramaTeam/Llamarama/files/8371298/crash-2022-03-29_14.12.17-client.txt)

**Comment by 0xmycf** [comment]
It seems to be some kind of casting problem 

java.lang.ClassCastException: class net.minecraft.class_638 cannot be cast to class net.minecraft.class_3218


I can look at it later or tomorrow if no one is available.


Thank you for reporting it!

Is there any other information that might be useful for us? What could we do to replicate the bug?
