### ISSUE TITLE
Bumblelama crashma

### ISSUE THREAD

**Issue by TheButterbrotMan** [ArshiaDPG/Llamarama#23]
**Describe the bug**
Server crashes cuz of Bumblelama and byg.

**To Reproduce**
Download my modpack, wander around.
https://www.curseforge.com/minecraft/modpacks/deathdusk

**Expected behavior**
Do not crash.

**Game Instance Information:**
- Game Version.
1.18.2
- Are there other mods in your instance?
- Yes.
- How many of them?
- 600+

**Crash Information(if relevant):**
https://bytebin.lucko.me/MMRizTsaXu

**Comment by 0xmycf** [comment]
It's this again: `BumbleLlamaEntity.tryGrowPlant`. I can't investigate until Monday. Maybe Joe can.

**Comment by 0xJoeMama** [comment]
Okay, I am gonna be honest, I have no idea about this. I am literally doing as many checks as I can and as many as the vanilla interface provides. I can't think of a way to fix this.

Reference: https://github.com/LlamaramaTeam/Llamarama/blob/45bf71be480819e43a140c7c2a0c0231218232ef/src/main/java/io/github/llamarama/team/common/entity/bumbllama/BumbleLlamaEntity.java#L132

**Comment by 0xJoeMama** [comment]
Could you try normally bonemealing that praire grass block?

**Comment by TheButterbrotMan** [comment]
> Could you try normally bonemealing that praire grass block?

Nothing, happens.

**Comment by TheButterbrotMan** [comment]
https://bytebin.lucko.me/svs8P3HahL This is in log then

**Comment by 0xJoeMama** [comment]
Well it seems like this is an issue from the byg mod not ours. I mean it does make sense. I can open an issue on that mod and redirect it here. Gimmeh one second.

**Comment by 0xJoeMama** [comment]
We switched to catching any thrown exceptions. This should handle this issue and prevent crashing but still give crashlogs featuring a report of the issue. Thank you for reporting!
