### ISSUE TITLE
Model Render Distance Bug

### ISSUE THREAD

**Issue by MachuMachu** [ArshiaDPG/Llamarama#28]
Llamas added by the mod doesn't render until you are very near to one (like 3 to 5 blocks). The particles surrounding the azaleas are rendered even afar.
Only really noticed with the azalea and honey llama, probably with the woolly llama as well.

Mod version: 1.6.4

**Comment by 0xJoeMama** [comment]
Identified. Will fix tomorrow, Thank you for your report!

**Comment by 0xJoeMama** [comment]
Jesus Christ I am stupid. Well the latest commit should fix this issue so I am closing this. Thank you again!
