### ISSUE TITLE
Llamarama crash 

### ISSUE THREAD

**Issue by V-lpen** [ArshiaDPG/Llamarama#33]
**Describe the bug**
Server crash when playing on my modded SMP with Llamarama.

**To Reproduce**
I am unsure how or why its crashing in the first place, the logs just point to here.

**Expected behavior**
No crash

**Screenshots**
N/A

**Game Instance Information:**
- Game Version. Fabric 1.18.2
*Keep in mind you need to be using the latest available version of the mod for each corresponding minecraft version.*
*Also, for older versions of the game, we will only respond to issues that either cause security concerns or game breaking behavior.*
- Are there other mods in your instance? Yes
- How many of them? A lot of mods. A full list can be seen in the crash report. 

**Crash Information(if relevant):**
- A crash log from when you got the issue(preferably in the form of a paste NOT a file). 
- https://mcpaste.io/ce022529c831968f
- A normal log of your game when a crash didn't occur.
- https://mcpaste.io/2ec0da22c0e2090d normal logs

**Comment by 0xJoeMama** [comment]
The issue was on my part because I had written wrong calculations that could lead to negative distance values which the game doesn't account for. Thank you for your report!

**Comment by 0xJoeMama** [comment]
I will make a release today closing this issue,

**Comment by 0xJoeMama** [comment]
#35 closes this however I may not release it today because I am waiting on some responses on other issues.
