### ISSUE TITLE
Heavy TPS Issues

### ISSUE THREAD

**Issue by TheButterbrotMan** [ArshiaDPG/Llamarama#34]
Im experiencing heavy tps issues while using llamarama in my modpack. I think its caused by the Wandering Lama Traders. But im not sure.

**Comment by 0xJoeMama** [comment]
I suggest using a performance analysis mod like carpet to see what is affecting your TPS. A claim like "I think...But im not sure" will not get us anywhere, especially considering the size of the modpack(assuming it's deathdusk you are talking about).

**Comment by TheButterbrotMan** [comment]
I did use spark for this. Spark clearly states your mod is eating TPS on my server. After I removed it I had thousands of entity llamarama: trader missing in my log.

**Comment by 0xJoeMama** [comment]
> 

Could you provide the spark report for this?

**Comment by 0xJoeMama** [comment]
I am still awaiting the spark report. From the profiling I have done on my part our mobs aren't that big a lag causer. I will attempt to profile an instance again today but I feel without the spark report or the aforementioned log I won't be able to be of much help.

**Comment by 0xJoeMama** [comment]
Maybe the number of entities is causing an issue. I actually have debated about making Caravan traders despawn if none of their trades have ever been used. That would remove all traders except the ones players have actually found. I will consider that as a solution, however I still wish to see the log and the spark report. Furthermore the following link shows the result of placing 10 creepers and 10 caravan traders in a world. As you can see the caravan trader tick method, takes so little time that my profiler can't even detect the stack entering the method: https://streamable.com/zgzg0r

**Comment by TheButterbrotMan** [comment]
Sadly I don't have this spark log anymore.

**Comment by TheButterbrotMan** [comment]
> Maybe the number of entities is causing an issue. I actually have debated about making Caravan traders despawn if none of their trades have ever been used. That would remove all traders except the ones players have actually found. I will consider that as a solution, however I still wish to see the log and the spark report. Furthermore the following link shows the result of placing 10 creepers and 10 caravan traders in a world. As you can see the caravan trader tick method, takes so little time that my profiler can't even detect the stack entering the method: https://streamable.com/zgzg0r

But I think that's probably the reason. There was just a lot of them.
