### ISSUE TITLE
[1.18.1] Too many Llamas in Caves

### ISSUE THREAD

**Issue by pewblaze** [ArshiaDPG/Llamarama#9]
I really love the new Llamas, but the spawnrate for the Mossy Ones is insane D: 
I used the Mod "observable" & counted 446 Llamas in total ^^" D: 
[2022-01-29--02.37.25.txt](https://github.com/LlamaramaTeam/Llamarama/files/7962761/2022-01-29--02.37.25.txt)
I counted the Llamas in the file.

Here a screenshot:
![2022-01-29_02 36 21](https://user-images.githubusercontent.com/96242065/151642480-468fd0a7-01bb-4869-ab99-1ca1b200a942.png)

I would love a config file, where you could change the spawnrates :) 
What can i do about the amount of LLamas? ^^"

**Comment by 0xJoeMama** [comment]
This is a bug, thank you for reporting!

The intended behavior is for mossy llamas to spawn quite rarely in Lush Caves, as you can see in the readme. I will get to fixing it as soon as possible once I have the time.
